### ISSUE TITLE
lndconnect support for easy Zap integration

### ISSUE THREAD

**Issue by JimmyMow** [wbobeirne/joule-extension#129]
### Description of the Feature or Idea

I think it would be cool if Joule supported [lndconnect](https://github.com/LN-Zap/lndconnect/blob/master/lnd_connect_uri.md) (or some format for passing auth info)

With this we (Zap) can host a "Connect to Joule" type of button offering much cleaner onboarding UX for users. 

### Existing Example(s) of Feature

User downloads Zap and Joule. Syncs to the chain and opens channels in Zap, clicks "Connect to Joule" and is authed into Joule.

**Comment by wbobeirne** [comment]
I've taken a look at this, and there are two key problems:

1. Joule exists only in the browser context, so there's not a way to have a link clicked in another context communicate with Joule, unlike native apps that can register a custom URI handler. This would require Joule to have a native component, as outlined in #106.
2. The current lndconnect format doesn't distinguish between the REST and gRPC APIs (and based on the examples, assumes gRPC) but Joule needs to use the REST API due to browser limitations.

I'm all in favor of being compatible with this URI format, but I think it would require a native application on my end.

**Comment by JimmyMow** [comment]
Ah ok, makes sense. well, I will close this issue for now. Hopefully something simpler will arise in the future
