### ISSUE TITLE
Show your node's pubkey (and connection info?)

### ISSUE THREAD

**Issue by wbobeirne** [wbobeirne/joule-extension#160]
### Description of the Feature or Idea

Just now realizing there's no way to get your own node's pubkey in an easy copyable way. Perhaps clicking on your icon should show it? Bonus points for if we can expose the full connection string, e.g. `[pubkey]@ip:port`. Not all node setups will allow for connecting that way, but many should. 

#### Zap

<img width="1008" alt="screen shot 2019-02-05 at 9 12 49 pm" src="https://user-images.githubusercontent.com/649992/52316727-d064bf80-298a-11e9-8c1a-6d63c43d252f.png">

**Comment by callmekurisu** [comment]
Pretty much done with this. Just wanted to post a demo before I submit code for review. This was done under the premise that only the Node URI will be display for public node which have ```externalip``` set in their lnd.conf otherwise it will only show ```identity_pubkey``` in the nodeinfo (state.node.nodeInfo
). Is that correct? Also, the modal displays after clicking the Identicon by the alias/pubkey. 

![nodeuri](https://user-images.githubusercontent.com/13033037/52908002-c8ced180-323a-11e9-843a-dbec99a7a33c.png)
