### ISSUE TITLE
IDIOT alert!! - Warn users if they are trying to send BTC directly to LND addresses!

### ISSUE THREAD

**Issue by OfficialBigAl** [wbobeirne/joule-extension#202]
Hi - I was tired and not paying full attention this morning and accidentally post my LND address into the BTC destination.

1) Is there some error checking to prevent other bleary eye'd idiots from sending funds into oblivion?

2) Is there any hope of retrieving sats from below tx?
https://blockstream.info/tx/ef7d6872b9ec83b9b3f410d7d83d021040429b82e60a3c7a3cefc1a2542d3111?expand

All the best - Love your work!

**Comment by wbobeirne** [comment]
Hey @OfficialBigAl, sorry that happened. Pretty honest mistake, very understandable. Ideally this should be accounted for in LND so that not every client has to handle this mistake individually. I've made an issue on `lnd` for this, and I'll see what they say. But if they don't want to implement it at the node level, I'll surely add it to Joule to prevent sending to yourself.

As for getting the money back, I have to imagine it's possible given that the private key that generated your node's pubkey presumably _should_ also be able to sign a transaction. However, I couldn't really begin to tell you where to start putting that together, sorry. As noted in the lnd issue, it might be nice if they provide an RPC command to do that for you.

Apologies for the trouble, but I'm glad it wasn't a life-changing amount of money.

**Comment by wbobeirne** [comment]
Looks like the folks working on LND are going to patch this up, I'm happy to see. In that case, I'll close this issue for now as I think it'll be handled upstream. Thanks for the report though, it unfortunately often takes someone to fall in the hole before devs know it needs to be covered up.
