### ISSUE TITLE
Install link is broken

### ISSUE THREAD

**Issue by decentropy** [wbobeirne/joule-extension#311]
This URL:
https://chrome.google.com/webstore/detail/joule/aejmoogjdllanidlpfjmmmmimfaficio

Gives 404 page:

404. That’s an error.
The requested URL was not found on this server. That’s all we know.

**Comment by Janaka-Steph** [comment]
Same on FF!

**Comment by chpio** [comment]
or did it just got deleted from the chrome store?

**Comment by wbobeirne** [comment]
Hey y'all, sorry for my delinquency on this. I've posted on Twitter a couple times about this, but haven't updated the readmes or posted issues for some of this stuff.

Joule got delisted from the Firefox extension store since their team couldn't reproduce the builds. A lot of work has been done (#295) to get them deterministic, but I hadn't actually gotten around to re-publishing there. But hopefully they'll accept it no problem.

The Chrome extension store on the other hand is more of a problem. Joule was delisted because they claimed the extension was asking for too many permissions for what it was doing. I was unable to appeal this, and will need to refactor the widget a little bit to remove some of the permissions it asks for to do what it does. They've also put out a new spec that extensions need to conform to (Manifest v3) and since Joule was delisted, it wasn't grandfathered in. Joule uses manifest v2 right now, and will need some rewriting to move over.

I'm open to anyone who wants to take on doing the conversion, otherwise it'll probably be some time before I get to this as I haven't been able to devote any time to Joule for a while. In the mean time, if folks need a WebLN lightning browser extension, people can check out [Alby](https://chrome.google.com/webstore/detail/alby-bitcoin-lightning-wa/iokeahhehimjnekafflcihljlcjccdbe) which our very own Joule contributor @bumi has been working diligently on.

Really sorry for leaving things as they are!

**Comment by mariano-dim** [comment]
hi man, could you enable the link please?

**Comment by wbobeirne** [comment]
@mariano-dim please read the comment above, it's not something I can just enable. You're welcome to install the latest release manually though!

**Comment by ndesanjo** [comment]
Is Joule web browser still active?

**Comment by wbobeirne** [comment]
I've updated the README to indicate that the project is no longer being actively developed.
