### ISSUE TITLE
Joule tries to connect to remote node without macaroon.

### ISSUE THREAD

**Issue by musdom** [wbobeirne/joule-extension#48]
I can't get Joule to connect to my remote node. It seems like it is trying to connect before presenting me with the macaroon upload page? I am able to curl to my lnd's REST server and getinfo just fine.

**Comment by wbobeirne** [comment]
Yep, this is intended behavior. Joule makes this requesting expecting it to fail, but it looks to make sure it fails in the right way with a missing macaroon error, and not another error. 

If you're seeing an error during this process, make sure you can open the url in the browser rather than curl. This is most commonly an issue with your browser not liking lnd's self signed certificate. You have to tell it to ignore it (which is reasonably safe to do, since it's running locally.) The error message should have an easy link to click to do this.

Let me know if that solves it for you! Hoping to find a better workaround for this soon.

**Comment by musdom** [comment]
Ah, ok I got it to work now! Looks great!

**Comment by otaviobps** [comment]
I'm getting the same error. Is SSL mandatory? I'm trying to connect thru http, but I always get the `Failed to fetch` message

**Comment by wbobeirne** [comment]
Unfortunately yes, LND has no non-https method. Did you follow the instructions in the error message? You could also try and [follow this guide](https://github.com/openoms/bitcoin-tutorials/blob/master/JouleToRaspiBlitz.md) (Meant for raspiblitz, but works pretty well for most node setups.)

**Comment by otaviobps** [comment]
I was missing the `tlsextraip` config. Thanks!
