### ISSUE TITLE
My suggestions for lightningjoule extension

### ISSUE THREAD

**Issue by bitcoinuser** [wbobeirne/joule-extension#59]
Hi, 

First of all, thanks for developing lightningjoule extension. 

Suggestions:

1- I think shouldn't have an option to deposit.
2- I think should only have option to send and request bitcoin lightning payments. Shouldn't have option to send payments to bitcoin addresses.
3- I think should have an option to mirror Android Bitcoin lightning wallets with lightningjoule extension using bluetooth tecnology. Look like is possible: (https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web)
4- I don't see why is necessary to show channels tab on lightningjoule.
5- I don't think you should add options like open or close channels.
6- I think the balance should have a better design like the Brave one:

![captura de tela de 2018-12-02 19-32-23](https://user-images.githubusercontent.com/1178856/49345239-3d956500-f669-11e8-85f6-c1ff7edc49dd.png)

**Comment by bitcoinuser** [comment]
I think you should keep lightningjoule as much simple as possible.

**Comment by wbobeirne** [comment]
Hey, thanks for the feedback!

While I get where you're coming from with 1, 2, 4, & 5 about keeping Joule simple, I think that due to some of the rough edges of the current state of Lightning, a lot of these options will be necessary to have a good experience. Not to mention that almost all lightning users are power users given the nature of how Joule works today, with setting up a node. Perhaps as the default node experience gets better with things like autopilot and custodial nodes, some of these options can be moved to advanced menus.

As for 3, while the technology for a phone and an extension to communicate _at all_ exists, none of these phone wallets are exposing their API, and most don't allow for invoice generation due to the spotty nature of phone connections and lack of static IP. I don't think we'll be seeing this kind of functionality any time soon, but if a phone app developer would like to work with me on this, I'd be more than open to it. But it's not simply a matter of opening a bluetooth connection to your phone, there's a lot more that would need to be built out.

Can you elaborate on what it is you'd like to see changed with 6?
