### ISSUE TITLE
Make required password to spend optional.

### ISSUE THREAD

**Issue by bitcoinuser** [wbobeirne/joule-extension#96]
Make required password to spend optional.

**Comment by wbobeirne** [comment]
This has definitely been on my radar in a big way. Currently the way this works is that your admin macaroon is stored in chrome extension storage, encrypted with the password you setup initially. Every time you want to make a spend, it fetches the encrypted macaroon, asks you for your password to decrypt it, and stores it in memory until the current session is done (e.g. closing of the popup, prompt window, or options tab.)

There are a few ways to work around this:
1. Store the admin macaroon unencrypted. I'm not willing to do this, since I think it's a terrible security practice, and I don't want to be responsible for lost user funds.
2. Keep the unencrypted macaroon in the background script memory, so that it's not lost each time the popup / prompt / options tab is closed. This would allow us to keep it in memory until either a determined interval (e.g. 30 minutes of inactivity), until the session has ended (e.g. chrome process is killed / computer restarted) or some kind of user-initiated logout. I think there's potential for security issues here if chrome's sandboxing is compromised in some way, but we'd probably have bigger issues than this if that were the case.
3. Wait until LND supports granular macaroon generation. This way I could generate a specific macaroon that is limited, and keep that unencrypted. Worst case, the user loses some small amount of money.

I'm currently leaning towards 2, since that could be implemented today. It's also what Metamask does, so I'm not particularly worried about the security implications.
